### ISSUE TITLE
connections的采集看起来不太对

### ISSUE THREAD

**Issue by wavelet123** [chenzhe07/zabbix_mysql#1]
你好，
connections的采集信息只有3~5，看起来不太对。
而且innodb_transactions的采集，请问下是如何处理的。

谢谢

**Comment by arstercz** [comment]
Connections 取得是系统状态参数的最新值, zabbix 的图像中使用 avg 计算两次采集数据的差值的平均数, 为 3 话表示最近一段时间新连接的平均值为 3, 如果你那边想看到最新的总数, 可以将 zabbix 中图像的 avg 函数换掉.  innodb_transactions的采集是通过分析 `show innodb status` 得到, 更具体的可以看看 `mymonitor.pl`.

**Comment by wavelet123** [comment]
谢谢回复，能不能给个QQ或者email，可以请教一下。

**Comment by arstercz** [comment]
可以 qq 联系:   510621028
